In [1]:
import numpy as np
import pandas as pd

In [7]:
data_g000=np.load('/Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/test_output/event000001016_g000.npz')

In [8]:
lst=data_g000.files
for item in lst:
    print(item)
    print(data_g000[item])

X
[[ 0.03206385 -0.3723127  -0.482952  ]
 [ 0.0326642  -0.6827858  -0.451418  ]
 [ 0.03229556 -0.52464294 -0.441377  ]
 ...
 [ 1.024662    0.3646726  -0.0162    ]
 [ 1.0194191   0.38497132 -0.0162    ]
 [ 1.0212373   0.627219   -0.0486    ]]
y
[0. 0. 0. ... 0. 0. 0.]
Ri_rows
[ 574  574  574 ... 3280 3280 3280]
Ri_cols
[    3     7    31 ... 30850 30851 30855]
Ro_rows
[   9   10   13 ... 3156 3156 3156]
Ro_cols
[    0     1     2 ... 30853 30854 30855]


In [11]:
data_g000_original= np.load('/Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/data/example_event/graph-no-cut/event000001016_g000.npz')

In [12]:
lst=data_g000_original.files
for item in lst:
    print(item)
    print(data_g000_original[item])

X
[[ 0.03280041 -0.7299177  -0.209357  ]
 [ 0.07232435 -0.7681164  -0.466794  ]
 [ 0.03144391  0.89982915 -0.25302202]
 ...
 [ 0.03193842 -0.183536   -0.309327  ]
 [ 0.35985827  0.9162174  -0.48367998]
 [ 0.49690026  0.27459607 -0.7108    ]]
y
[1. 0. 0. ... 0. 0. 0.]
Ri_rows
[   1    1    1 ... 2644 2644 2644]
Ri_cols
[    0   530  1359 ... 17152 17269 17316]
Ro_rows
[   0    0    0 ... 2643 2644 2644]
Ro_cols
[    0     1     2 ... 17837 18837 18838]
